# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yerradi <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 23:00:11 by yerradi           #+#    #+#              #
#    Updated: 2018/10/08 13:54:35 by yerradi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=libft.a
CC=gcc
CFLAGS=-Wall -Wextra -Werror
RM=rm -f
LDFLAGS=-L.
LDLIBS=-lft
SRC = ft_bzero.c ft_memset.c ft_memcpy.c\
	  ft_memccpy.c ft_memmove.c ft_memchr.c\
	  ft_memcmp.c ft_strlen.c ft_strcpy.c\
	  ft_strdup.c ft_strncpy.c ft_strcat.c\
	  ft_strncat.c ft_strlcat.c ft_strlcat.c\
	  ft_strchr.c ft_strrchr.c ft_putchar.c\
	  ft_putstr.c ft_putchar_fd.c ft_putstr_fd.c\
	  ft_strcmp.c ft_strncmp.c ft_strstr.c\
	  ft_strnstr.c ft_atoi.c ft_isalpha.c\
	  ft_isdigit.c ft_isalnum.c ft_isascii.c\
	  ft_isprint.c ft_toupper.c ft_tolower.c\
	  ft_memalloc.c ft_memdel.c ft_strnew.c\
	  ft_strdel.c ft_strclr.c ft_striter.c\
	  ft_striteri.c ft_strmap.c ft_strmapi.c\
	  ft_strequ.c ft_strnequ.c ft_strsub.c\
	  ft_strjoin.c ft_isspace.c ft_putendl.c\
	  ft_putendl_fd.c ft_strtrim.c ft_putnbr.c\
	  ft_putnbr_fd.c ft_itoa.c ft_strsplit.c\
	  ft_lstnew.c ft_lstdelone.c ft_abs.c\
	  ft_lstdel.c ft_lstadd.c ft_lstiter.c\
	  ft_lstmap.c ft_power.c ft_sqrt.c\
	  ft_count_words.c
OBJ = $(SRC:.c=.o)

$(NAME): $(OBJ)
		ar rc $(NAME) $(OBJ)
		ranlib $(NAME)

%.o: %.c
		$(CC) -I. -o $@ -c $? $(CFLAGS)

all: $(NAME)

clean:
		$(RM) $(OBJ)

fclean: clean
		$(RM) $(NAME)

re: fclean all